# -*- coding: utf-8 -*-
#
# export-tag Add-on for Anki
# Copyright (C)  2021 RisingOrange
#
# This file was automatically generated by Anki Add-on Builder v0.1.5-beta.6
# It is subject to the same licensing terms as the rest of the program
# (see the LICENSE file which accompanies this program).
#
# WARNING! All changes made in this file will be lost!

"""
Initializes generated Qt forms/resources
"""

__all__ = [
    "tag_export_dialog"
]

from . import tag_export_dialog
