# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/tag_export_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(480, 169)
        self.gridLayout_6 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.button_export = QtWidgets.QPushButton(Dialog)
        self.button_export.setObjectName("button_export")
        self.gridLayout_6.addWidget(self.button_export, 8, 7, 1, 1)
        self.toolButton_website = QtWidgets.QToolButton(Dialog)
        self.toolButton_website.setMaximumSize(QtCore.QSize(31, 31))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/CustomBackground/AnKingSmall.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_website.setIcon(icon)
        self.toolButton_website.setIconSize(QtCore.QSize(31, 31))
        self.toolButton_website.setObjectName("toolButton_website")
        self.gridLayout_6.addWidget(self.toolButton_website, 0, 1, 1, 1)
        self.toolButton_instagram = QtWidgets.QToolButton(Dialog)
        self.toolButton_instagram.setMaximumSize(QtCore.QSize(31, 31))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/CustomBackground/Instagram.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_instagram.setIcon(icon1)
        self.toolButton_instagram.setIconSize(QtCore.QSize(31, 31))
        self.toolButton_instagram.setObjectName("toolButton_instagram")
        self.gridLayout_6.addWidget(self.toolButton_instagram, 0, 5, 1, 1)
        self.toolButton_facebook = QtWidgets.QToolButton(Dialog)
        self.toolButton_facebook.setMaximumSize(QtCore.QSize(31, 31))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/CustomBackground/Facebook.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_facebook.setIcon(icon2)
        self.toolButton_facebook.setIconSize(QtCore.QSize(31, 31))
        self.toolButton_facebook.setObjectName("toolButton_facebook")
        self.gridLayout_6.addWidget(self.toolButton_facebook, 0, 6, 1, 1)
        self.toolButton_patreon = QtWidgets.QToolButton(Dialog)
        self.toolButton_patreon.setMaximumSize(QtCore.QSize(171, 26))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/CustomBackground/Patreon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_patreon.setIcon(icon3)
        self.toolButton_patreon.setIconSize(QtCore.QSize(200, 31))
        self.toolButton_patreon.setObjectName("toolButton_patreon")
        self.gridLayout_6.addWidget(self.toolButton_patreon, 0, 3, 1, 2)
        self.toolButton_youtube = QtWidgets.QToolButton(Dialog)
        self.toolButton_youtube.setMaximumSize(QtCore.QSize(31, 31))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/CustomBackground/YouTube.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_youtube.setIcon(icon4)
        self.toolButton_youtube.setIconSize(QtCore.QSize(31, 31))
        self.toolButton_youtube.setObjectName("toolButton_youtube")
        self.gridLayout_6.addWidget(self.toolButton_youtube, 0, 2, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.lineedit_tag = QtWidgets.QLineEdit(Dialog)
        self.lineedit_tag.setClearButtonEnabled(True)
        self.lineedit_tag.setObjectName("lineedit_tag")
        self.verticalLayout.addWidget(self.lineedit_tag)
        self.gridLayout_6.addLayout(self.verticalLayout, 3, 0, 1, 8)
        self.toolButton_patreon.raise_()
        self.toolButton_facebook.raise_()
        self.toolButton_instagram.raise_()
        self.toolButton_website.raise_()
        self.toolButton_youtube.raise_()
        self.button_export.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Export tag"))
        self.button_export.setText(_translate("Dialog", "Export"))
        self.toolButton_website.setText(_translate("Dialog", "..."))
        self.toolButton_instagram.setText(_translate("Dialog", "..."))
        self.toolButton_facebook.setText(_translate("Dialog", "..."))
        self.toolButton_patreon.setText(_translate("Dialog", "..."))
        self.toolButton_youtube.setText(_translate("Dialog", "..."))
        self.label.setText(_translate("Dialog", "Tag to export:"))
